=== folio-org/courses/ramls/course.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "description": "A course offered by the institution",
    "additionalProperties": false,
    "properties": {
        "id": {
            "type": "string",
            "description": "UUID to identify this course",
            "$ref": "uuid.json"
        },
        "name": {
            "type": "string",
            "description": "The name of course"
        },
        "description": {
            "type": "string",
            "description": "A description of the course"
        },
        "departmentId": {
            "type": "string",
            "description": "The department that this course belongs to",
            "$ref": "uuid.json"
        },
        "courseListingId": {
            "type": "string",
            "description": "The course listing this course belongs to",
            "$ref": "uuid.json"
        },
        "courseNumber": {
            "type": "string",
            "description": "A unique code identifying this course"
        },
        "sectionName": {
            "type": "string",
            "description": "A text field denoting this course's section"
        },
        "metadata": {
            "type": "object",
            "$ref": "raml-util/schemas/metadata.schema"
        }
    },
    "required": [
        "name",
        "departmentId",
        "courseListingId"
    ]
}

=== folio-org/courses/src/main/resources/sample-data/courses/Course001.json
{
  "id": "04ea3db8-e42a-4e18-b98d-cc447e3f9a57",
  "name": "Calculus 201",
  "description": "Advanced differentiation and integration",
  "departmentId": "1fc91124-cd2a-4fae-9ae4-40368d80982d",
  "courseListingId": "cef52efb-b3fd-4450-9960-1745026a99d1",
  "courseNumber": "67890",
  "sectionName": "Sole"
}

=== folio-org/courses/src/main/resources/sample-data/courses/Course000.json
{
  "id": "83034b0a-bf71-4495-b642-2e998f721e5d",
  "name": "Calculus 101",
  "description": "Basic differentiation and integration",
  "departmentId": "1fc91124-cd2a-4fae-9ae4-40368d80982d",
  "courseListingId": "c03bcba3-a6a0-4251-b316-0631bb2e6f21",
  "courseNumber": "12345",
  "sectionName": "Main"
}

=== folio-org/courses/src/main/resources/sample-data/courses/Course003.json
{
  "id": "aabf7f46-9a38-4c72-b3b1-45a55077436a",
  "name": "Intro to Palaeontology",
  "description": "Study of ancient life",
  "departmentId": "1566841c-51ce-4d4c-aa09-0ea21b00904a",
  "courseListingId": "1049e672-dcde-4c7c-b95b-edf9f60c6cbd",
  "courseNumber": "24680",
  "sectionName": "Sole"
}
