=== folio-org/courses/ramls/courselisting.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "description": "An actual instantiation in time and space of a course",
    "additionalProperties": false,
    "properties": {
        "id": {
            "type": "string",
            "description": "UUID for this listing",
            "$ref": "uuid.json"
        },
        "registrarId": {
            "type": "string",
            "description": "The registration id"
        },
        "externalId": {
            "type": "string",
            "description": "An external identifier associated with this listing"
        },
        "servicepointId": {
            "type": "string",
            "description": "The ID of the service point associated with this listing's reserves",
            "$ref": "uuid.json"
        },
        "locationId": {
            "type": "string",
            "description": "The ID of the location associated with this listing's reserves",
            "$ref": "uuid.json"
        },
        "termId": {
            "type": "string",
            "description": "The ID of the term for this listing",
            "$ref": "uuid.json"
        },
        "termObject": {
            "type": "object",
            "description": "The term associated with this listing",
            "$ref": "term.json"
        },
        "courseTypeId": {
            "type": "string",
            "description": "The ID of the course type for this listing",
            "$ref": "uuid.json"
        },
        "courseTypeObject": {
            "type": "object",
            "description": "The course type associated with this listing",
            "$ref": "coursetype.json"
        },
        "metadata": {
            "type": "object",
            "$ref": "raml-util/schemas/metadata.schema"
        }
    },
    "required": [
        "termId"
    ]
}

=== folio-org/courses/src/main/resources/sample-data/courselistings/CourseListing000.json
{
  "id": "c03bcba3-a6a0-4251-b316-0631bb2e6f21",
  "registrarId": "external1",
  "externalId": "external2",
  "servicepointId": "3a40852d-49fd-4df2-a1f9-6e2641a6e91f",
  "locationId": "53cf956f-c1df-410b-8bea-27f712cca7c0",
  "termId": "cd1eb7ed-2704-4b6a-9037-d7f1a5351f6b",
  "courseTypeId": "f5063ee8-b18c-402b-b0c9-1b0f93d8570b"
}
